src/Chamilo/CoreBundle/Form/BranchType.php
<?php
/* For licensing terms, see /license.txt */

namespace Chamilo\CoreBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Entity;

class BranchType extends AbstractType
{
    /**
     * Builds the form
     * For form type details see:
     * http://symfony.com/doc/current/reference/forms/types.html
     *
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builderData = $builder->getData();

        $parentIdDisabled = false;
        if (!empty($builderData)) {
            $parentIdDisabled = true;
        }

        $builder
            ->add('branch_name', 'text')
            ->add('branch_type', 'choice', array('choices' => array('remote_child', 'local_child', 'local_parent', 'remote_parent')))
            //->add('parent_id', 'choice', array('choices'=> array(), 'required' => false))
            ->add('parent_id', 'text', array('required' => false, 'disabled' => $parentIdDisabled))
            //->add('parent_id', 'choice', array('choices'=> array(1 => 'jjaa',2=>'ddd'), 'required' => false))
            ->add('branch_ip', 'text')
            ->add('latitude', 'text')
            ->add('longitude', 'text')
            ->add('dwn_speed', 'text')
            ->add('up_speed', 'text')
            ->add('longitude', 'text')
            ->add('delay', 'text')
            ->add('admin_mail', 'email')
            ->add('admin_name', 'text')
            ->add('admin_phone', 'text', array('required' => false))
            ->add('last_sync_trans_date', 'datetime', array(
                'data' => new \DateTime()
                )
            )
            ->add('last_sync_type', 'text')
            ->add('last_sync_trans_id', 'text')
            ->add('ssl_pub_key', 'text')
            ->add('last_sync_trans_id', 'text')
            ->add('access_url_id', 'text')
            ->add('submit', 'submit');


    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Chamilo\CoreBundle\Entity\BranchSync'
            )
        );
    }

    public function getName()
    {
        return 'branch';
    }
}

src/Chamilo/CoreBundle/Controller/User/ProfileController.php
<?php
/* For licensing terms, see /license.txt */

namespace Chamilo\CoreBundle\Controller\User;

use Chamilo\CoreBundle\Controller\BaseController;
use Silex\Application;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Response;


/**
 * Class ProfileController
 * @package Chamilo\CoreBundle\Controller
 */
class ProfileController extends BaseController
{

    /**
     * My files
     * @Route("/{username}/files")
     * @Method({"GET"})
     */
    public function fileAction($username)
    {
        if ($this->getUser()->getUsername() != $username) {
            return $this->abort(401);
        }

        $userId = \UserManager::get_user_id_from_username($username);
        $userInfo = api_get_user_info($userId);

        $this->getTemplate()->assign('driver_list', 'PersonalDriver,DropBoxDriver');

        $editor = $this->getTemplate()->renderTemplate(
            $this->getHtmlEditor()->getEditorStandAloneTemplate()
        );

        $this->getTemplate()->assign('user', $userInfo);
        $this->getTemplate()->assign('editor', $editor);

        $response = $this->getTemplate()->renderTemplate(
            $this->getTemplatePath().'files.tpl'
        );
        return new Response($response, 200, array());
    }

    /**
     * Gets that rm.wav sound
     * @Route("/{username}/sounds/{file}")
     * @Method({"GET"})
     */
    public function getSoundAction()
    {
        $file = api_get_path(LIBRARY_PATH).'elfinder/rm.wav';
        return $this->app->sendFile($file);
    }

    /**
     * {@inheritdoc}
     */
    public function getTemplatePath()
    {
        return 'user/';
    }
}

src/Chamilo/CoreBundle/Controller/User/UserController.php
<?php
/* For licensing terms, see /license.txt */

namespace Chamilo\CoreBundle\Controller\User;

use Symfony\Component\HttpFoundation\Response;
use Chamilo\CoreBundle\Controller\BaseController;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

/**
 * Class UserController
 * @package Chamilo\CoreBundle\Controller
 * @author Julio Montoya <gugli100@gmail.com>
 */
class UserController extends BaseController
{
    /**
     * @Route("/me")
     * @Method({"GET"})
     */
    public function indexAction()
    {
        $userInfo = api_get_user_info($this->getUser()->getUserId());

        $this->getTemplate()->assign('user', $userInfo);
        $response = $this->getTemplate()->renderTemplate($this->getTemplatePath().'me.tpl');
        return new Response($response, 200, array());
    }

    /**
     * @Route("/{username}")
     * @Method({"GET"})
     * @Template("ChamiloCoreBundle:User:profile.html.twig")
     */
    public function profileAction($username)
    {
        $userId = \UserManager::get_user_id_from_username($username);
        $userInfo = api_get_user_info($userId);

        return array(
            'user' =>  $userInfo,
            'form_send_message' => \MessageManager::generate_message_form('send_message'),
            'form_send_invitation' => \MessageManager::generate_invitation_form('send_invitation')
        );
    }

    /**
     * @Route("/online")
     * @Method({"GET"})
     */
    public function onlineAction(Application $app)
    {
        $response = $app['template']->renderLayout('layout_1_col.tpl');
        return new Response($response, 200, array());
    }

    /**
     * {@inheritdoc}
     */
    public function getTemplatePath()
    {
        return 'user/';
    }
}

src/Chamilo/CoreBundle/Resources/views/User/_form.html.twig
{% form_theme form '@ChamiloCore/User/forms.html.twig' %}

{{ form_errors(form) }}
{% include '@ChamiloCore/User/Form/_tabs.html.twig' %}
<br>
<div class="tab-content">
    {% include '@ChamiloCore/User/Form/_main.html.twig' %}
    {% include '@ChamiloCore/User/Form/_attributes.html.twig' %}
</div>
<hr>

{{ form_widget(form._token) }}

src/Chamilo/CoreBundle/Resources/views/User/create.html.twig
{% from '@ChamiloAdminTheme/Macros/actions.html.twig' import create %}

{{ form_errors(form) }}

<form action="{{ url }}" method="post" class="form-horizontal" {{ form_enctype(form) }} novalidate>
    {% include '@ChamiloCore/User/_form.html.twig' %}
    {{ create(url) }}
</form>

src/Chamilo/CoreBundle/Resources/views/User/forms.html.twig
{% extends 'form_div_layout.html.twig' %}

{% block choice_widget_collapsed %}
    {% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
    {{ parent() }}
{% endblock choice_widget_collapsed %}

{% block textarea_widget %}
    {% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
    {{ parent() }}
{% endblock textarea_widget %}

{% block form_widget_simple %}
    {% spaceless %}
        {% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
        {% set type = type|default('text') %}

        {% if 'file' == type %}
            <span class="btn-primary btn-lg file-overlay"><i class="icon-folder-open"></i> {{ 'sylius.form.choose_file'|trans }}</span>
        {% endif %}
        {{ parent() }}
    {% endspaceless %}
{% endblock form_widget_simple %}

{% block form_label %}
    {% spaceless %}
        {% set label_attr = label_attr|merge({'class': label_attr.class|default('col-lg-2') ~ ' control-label'}) %}
        {{ parent() }}
    {% endspaceless %}
{% endblock form_label %}

{% block money_widget %}
    {% spaceless %}
        <div class="input-group">
            <span class="input-group-addon">{{ money_pattern|replace({'{{ widget }}': ''}) }}</span>
            {{ block('form_widget_simple') }}
        </div>
    {% endspaceless %}
{% endblock money_widget %}

{% block percent_widget %}
    {% spaceless %}
        <div class="input-group">
            <span class="input-group-addon">%</span>
            {{ block('form_widget_simple') }}
        </div>
    {% endspaceless %}
{% endblock percent_widget %}

{% block datetime_widget %}
    {% spaceless %}
        {% if widget == 'single_text' %}
            {{ block('form_widget_simple') }}
        {% else %}
            <div class="form-group">
                {{ form_widget(form.date) }}
                {{ form_widget(form.time) }}
            </div>
        {% endif %}
    {% endspaceless %}
{% endblock datetime_widget %}

{% block date_widget %}
    {% spaceless %}
        {% if widget == 'single_text' %}
            {{ block('form_widget_simple') }}
        {% else %}
            {{ '{{ year }} / {{ month }} / {{ day }}'|replace({
            '{{ year }}':  form_widget(form.year, {'attr': {'style': 'display: inline; width: 100px;'}}),
            '{{ month }}': form_widget(form.month, {'attr': {'style': 'display: inline; width: 100px;'}}),
            '{{ day }}':   form_widget(form.day, {'attr': {'style': 'display: inline; width: 100px;'}}),
            })|raw }}
        {% endif %}
    {% endspaceless %}
{% endblock date_widget %}

{% block time_widget %}
    {% spaceless %}
        {% if widget == 'single_text' %}
            {{ block('form_widget_simple') }}
        {% else %}
            {% set vars = widget == 'text' ? { 'attr': { 'size': 1, 'style': 'width: 60px; display: inline;' }} : {} %}
            &nbsp;{{ form_widget(form.hour, vars) }}{% if with_minutes %}:{{ form_widget(form.minute, vars) }}{% endif %}{% if with_seconds %} {{ form_widget(form.second, vars) }}{% endif %}
        {% endif %}
    {% endspaceless %}
{% endblock time_widget %}

{% block form_row %}
    {% spaceless %}
        <div class="form-group{% if errors|length > 0 %} has-error{% endif %}">
            {{ form_label(form) }}
            <div class="col-lg-10">
                {{ form_widget(form) }}
                {% for error in errors %}
                    <span class="help-block form-error">
                {{
                error.messagePluralization is null
                ? error.messageTemplate|trans(error.messageParameters, 'validators')
                : error.messageTemplate|transchoice(error.messagePluralization, error.messageParameters, 'validators')
                }}
            </span>
                {% endfor %}
            </div>
        </div>
    {% endspaceless %}
{% endblock form_row %}

{% block sonata_media_type_widget %}
    <div class="col-xs-3 pull-left">
        {% if value is not empty and value.providerReference %}
            <div class="pull-left" style="margin-right: 5px">
                {% thumbnail value, 'admin' with {'class': 'img-polaroid media-object'} %}
            </div>

            {% if sonata_admin_enabled is defined and sonata_admin_enabled %}
                <a href="{{ url('admin_sonata_media_media_edit', {id: value.id}) }}"><strong>{{ value.name }}</strong></a>
            {% else %}
                <strong>{{ value.name }}</strong>
            {% endif %}
            <br />
            <span type="label">{{ value.providerName|trans({}, 'SonataMediaBundle') }}</span> ~ {{ value.context }}
        {% else %}
            <div class="pull-left" style="margin-right: 5px">
                <img src="{{ asset('bundles/sonatamedia/grey.png') }}" class="img-polaroid media-object" style="width: 85px; height: 85px"/>
            </div>
            <strong>{{ 'no_linked_media'|trans({}, 'SonataMediaBundle') }}</strong> <br />
            <span type="label">{{ form.vars['provider']|trans({}, 'SonataMediaBundle') }} ~ {{ form.vars['context']|trans({}, 'SonataMediaBundle') }}</span>
        {% endif %}
    </div>

    <div class="span3 pull-left">
        {{ 'link_media'|trans({}, 'SonataMediaBundle') }}
        {{ block('form_widget') }}
    </div>
{% endblock sonata_media_type_widget %}

src/Chamilo/CoreBundle/Resources/views/User/profile.html.twig
{% block left_column %}
    <script>
        function checkLength( o, n, min, max ) {
            if ( o.val().length > max || o.val().length < min ) {
                o.addClass( "ui-state-error" );
                //updateTips( "Length of " + n + " must be between " + min + " and " + max + "." );
                return false;
            } else {
                return true;
            }
        }

        function send_message_to_user(user_id) {
            var subject = $( "#subject_id" );
            var content = $( "#content_id" );
            $("#send_message_form").show();
            $("#send_message_div").dialog({
                modal:true,
                height:350,
                buttons: {
                    "{{ 'Send' | trans }}": function() {
                        var bValid = true;
                        bValid = bValid && checkLength( subject, "subject", 1, 255 );
                        bValid = bValid && checkLength( content, "content", 1, 255 );

                        if ( bValid ) {
                            var url = "{{ url('web.ajax') }}message.ajax.php?a=send_message&user_id="+user_id;
                            var params = $("#send_message_form").serialize();
                            $.ajax({
                                url: url+"&"+params,
                                success:function(data) {
                                    $("#message_ajax_reponse").html(data);
                                    $("#message_ajax_reponse").show();
                                    $("#send_message_div").dialog({ buttons:{}});
                                    $("#send_message_form").hide();
                                    $("#send_message_div").dialog("close");
                                    $("#subject_id").val("");
                                    $("#content_id").val("");
                                }
                            });
                        }
                    }
                },
                close: function() {
                }
            });
            $("#send_message_div").dialog("open");
            //prevent the browser to follow the link
        }

        function send_invitation_to_user(user_id) {
            var content = $( "#content_invitation_id" );
            $("#send_invitation_form").show();
            $("#send_invitation_div").dialog({
                modal:true,
                buttons: {
                    "{{ 'SendInvitation' | trans }}": function() {
                        var bValid = true;
                        bValid = bValid && checkLength( content, "content", 1, 255 );
                        if (bValid) {
                            var url = "{{ url('web.ajax') }}message.ajax.php?a=send_invitation&user_id="+user_id;
                            var params = $("#send_invitation_form").serialize();
                            $.ajax({
                                url: url+"&"+params,
                                success:function(data) {
                                    $("#message_ajax_reponse").html(data);
                                    $("#message_ajax_reponse").show();
                                    $("#send_invitation_div").dialog({ buttons:{}});
                                    $("#send_invitation_form").hide();
                                    $("#send_invitation_div").dialog("close");
                                    $("#content_invitation_id").val("");
                                }
                            });
                        }
                    }
                },
                close: function() {
                }
            });
            $("#send_invitation_div").dialog("open");
            //prevent the browser to follow the link
        }

        $(document).ready(function (){
            $("input#id_btn_send_invitation").bind("click", function(){
                if (confirm("'.trans('SendMessageInvitation', '').'")) {
                    $("#form_register_friend").submit();
                }
            });

            $("#send_message_div").dialog({
                autoOpen: false,
                modal    : false,
                width    : 550,
                height    : 300
            });

            $("#send_invitation_div").dialog({
                autoOpen: false,
                modal    : false,
                width    : 550,
                height    : 300
            });

        });
    </script>

    <div class="well social-background-content">
        <img src="{{ user.avatar }}"/>
    </div>

    <div class="well sidebar-nav">
        <ul class="nav nav-pills nav-stacked">
            <li>
                <a href="javascript:void(0);" onclick="javascript:send_message_to_user('{{ user.user_id }}');">
                    {{ 'SendMessage' | trans }}
                </a>
            </li>
            <li>
                <a href="javascript:void(0);" onclick="javascript:send_invitation_to_user('{{ user.user_id }}');">
                    {{ 'SendInvitation' | trans }}
                </a>
            </li>
        </ul>
    </div>

{% endblock %}

{% block right_column %}
    <span id ="message_ajax_reponse"></span>
    <div class="well_border">
        <h3>{{ user.complete_name }} @{{ user.username }} </h3>
    </div>
    {{ form_send_message }}
    {{ form_send_invitation }}
{% endblock %}